SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE categorie (
  IdCategorie		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  Libelle			VARCHAR(25)		NOT NULL,
  PRIMARY KEY (IdCategorie)
);

CREATE TABLE auteur (
  IdAuteur			INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  Nom 				VARCHAR(25)		NOT NULL,
  PRIMARY KEY (IdAuteur)
);

CREATE TABLE editeur (
  IdEditeur 		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  Nom 				VARCHAR(25)		NOT NULL,
  PRIMARY KEY (IdEditeur)
);

CREATE TABLE personne (
  IdPersonne		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  IdCompte	 		INT				NOT NULL,
  Nom 				VARCHAR(25)		NOT NULL,
  Prenom 			VARCHAR(25)		NOT NULL,
  DateNaissance 	DATE			NOT NULL,
  FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
  PRIMARY KEY (IdPersonne)
);
CREATE UNIQUE INDEX idx_personne_compte ON personne (IdCompte ASC);

CREATE TABLE ouvrage (
  IdOuvrage 		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  IdCategorie 		INT				NOT NULL,
  IdEditeur 		INT				NOT NULL,
  IdAuteur 			INT				NOT NULL,
  IdProprietaire	INT				NOT NULL,
  Titre 			VARCHAR(25)		NOT NULL,
  FOREIGN KEY (IdCategorie) REFERENCES categorie (IdCategorie),
  FOREIGN KEY (IdEditeur)	REFERENCES editeur (IdEditeur),
  FOREIGN KEY (IdAuteur)	REFERENCES auteur (IdAuteur),
  FOREIGN KEY (IdProprietaire)	REFERENCES personne(IdPersonne),
  PRIMARY KEY (IdOuvrage)
);

CREATE TABLE amitie (
  IdUtilisateur		INT				NOT NULL,
  IdAmi				INT				NOT NULL,
  FOREIGN KEY (IdUtilisateur) REFERENCES personne (IdPersonne),
  FOREIGN KEY (IdAmi) REFERENCES personne (IdPersonne),
  PRIMARY KEY (IdUtilisateur, IdAmi)
);

ALTER TABLE amitie
ADD CONSTRAINT fk_idAmi
FOREIGN KEY (idAmi)
REFERENCES personne (idPersonne)
ON DELETE CASCADE;

ALTER TABLE amitie
ADD CONSTRAINT fk_idUtilisateur
FOREIGN KEY (idUtilisateur)
REFERENCES personne (idPersonne)
ON DELETE CASCADE;


CREATE TABLE emprunt (
  IdEmprunteur 		INT				NOT NULL,
  IdOuvrage 		INT				NOT NULL,
  FOREIGN KEY (IdEmprunteur)   REFERENCES personne (IdPersonne),
  FOREIGN KEY (IdOuvrage)  	   REFERENCES ouvrage (IdOuvrage),
  PRIMARY KEY (IdEmprunteur, IdOuvrage)
);




