SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Nom 			VARCHAR(25)		NOT NULL,
  	Prenom 			VARCHAR(25)		NOT NULL,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE categorie (
  IdCategorie		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  Libelle			VARCHAR(25)		NOT NULL,
  PRIMARY KEY (IdCategorie)
);

CREATE TABLE auteur (
  IdAuteur			INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  Nom 				VARCHAR(25)		NOT NULL,
  PRIMARY KEY (IdAuteur)
);

CREATE TABLE editeur (
  IdEditeur 		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  Nom 				VARCHAR(25)		NOT NULL,
  PRIMARY KEY (IdEditeur)
);

CREATE TABLE ouvrage (
  IdOuvrage 		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
  IdCategorie 		INT				NOT NULL,
  IdEditeur 		INT				NOT NULL,
  IdAuteur 			INT				NOT NULL,
  Titre 			VARCHAR(25)		NOT NULL,
  FOREIGN KEY (IdCategorie) REFERENCES categorie (IdCategorie),
  FOREIGN KEY (IdEditeur)	REFERENCES editeur (IdEditeur),
  FOREIGN KEY (IdAuteur)	REFERENCES auteur (IdAuteur),
  PRIMARY KEY (IdOuvrage)
);

CREATE TABLE etreAmi (
  IdDemandeur 		INT				NOT NULL,
  IdRecepteur		INT				NOT NULL,
  statut			CHAR(1)			NOT NULL  DEFAULT 'P',
  FOREIGN KEY (IdDemandeur) REFERENCES compte (IdCompte),
  FOREIGN KEY (IdRecepteur) REFERENCES compte (IdCompte),
  CHECK ( statut IN ('P', 'C', 'V') ),
  PRIMARY KEY (IdDemandeur, IdRecepteur)
);

CREATE TABLE posseder (
  IdCompte 		INT				NOT NULL,
  IdOuvrage 		INT				NOT NULL,
  FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
  FOREIGN KEY (IdOuvrage)  REFERENCES ouvrage (IdOuvrage),
  PRIMARY KEY (IdCompte, IdOuvrage)
);

CREATE TABLE emprunter (
  IdEmprunteur 		INT				NOT NULL,
  IdProprietaire	INT				NOT NULL,
  IdOuvrage 		INT				NOT NULL,
  FOREIGN KEY (IdEmprunteur)   REFERENCES compte (IdCompte),
  FOREIGN KEY (IdProprietaire) REFERENCES compte (IdCompte),
  FOREIGN KEY (IdOuvrage)  	   REFERENCES ouvrage (IdOuvrage),
  PRIMARY KEY (IdEmprunteur, IdOuvrage, IdProprietaire)
);




